### ISSUE TITLE
Mongock BOM brings dependencies of different mongock versions

### ISSUE THREAD

**Issue by sdobrovolschi** [flamingock/mongock#215]
**Describe the bug** 

mongock-spring-v5:2.0.4 is binary incompatible with mongock-runner-core:4.3.3
The `ProfiledChangeLogService` can not invoke the ChangeLogService's constructor

See https://mvnrepository.com/artifact/com.github.cloudyrock.mongock/mongock-bom/4.3.3

**To Reproduce**

pom.xml

```
...
 <dependencies>
     <dependency>
        <groupId>com.github.cloudyrock.mongock</groupId>
        <artifactId>mongock-spring-v5</artifactId>
    </dependency>
    <dependency>
        <groupId>com.github.cloudyrock.mongock</groupId>
        <artifactId>mongodb-springdata-v3-driver</artifactId>
    </dependency>
 </dependencies>

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.3.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
<dependencyManagement>
...
```

**Screenshots**

<img width="553" alt="Screenshot 2021-02-14 at 16 48 37" src="https://user-images.githubusercontent.com/26041085/107879959-95d07e80-6ee4-11eb-9dd0-0ea1a02b0709.png">

**Comment by sdobrovolschi** [comment]
https://mvnrepository.com/artifact/com.github.cloudyrock.mongock/mongock-bom/4.3.4 - still a mix of 4.3.3 and 4.3.4

**Comment by dieppa** [comment]
No worries, that's fine. In this exceptional case, 4.3.3 and 4.3.4 are equivalent.
In next version 4.3.5 all the dependencies will share the same version, but that condition may not happen in future versions, so don't worry about that, as long as you place the mongock-bom, it will manage the versions for you.
