### ISSUE TITLE
Encourage encapsulation in Mongock

### ISSUE THREAD

**Issue by dieppa** [flamingock/mongock#339]
Make setters package-private for those fields which shouldn't be changed once built

**Comment by ghost** [comment]
Hello @dieppa,
I'd like to help with this

**Comment by dieppa** [comment]
Hello @mbuccat ,
this is a pretty easy one that can help you to know the code. The idea is easy, expose just what is needed. For example, right now, due to a PR, the method  `setChangelogMongoDatabase` in the class Mongock is public, so exposed to the outside. First this is not ideal because it's not intended to be modified after build via the builder, but even worse, it's not correct because if the changelog database is changed while the process is running, it could produced an undesired result.

There are two problems. First of them is Java: until JDK9 there is not a proper module model. 
So we have located class and builder in the same package(which is the same in all the submodules) to be able to access to package-private members. A better approach is to have the builder inside of the class itself, so it can access to the members, without need to expose them. So this brings the second problem, it need a deeper refactoring.


So there are two ways to do this: Doing in 2 steps. First step just fix wrong exposure of members. Second step implement refactoring.  The other way is jump to the refactor directly.
 I suggest the first approach.

**Comment by ghost** [comment]
Thanks for the tips! I'll go with your suggested approach

**Comment by dieppa** [comment]
Yeah, Actually I was about to tell you, as there is another person who wants to help with the  [refactor issue](https://github.com/cloudyrock/mongock/issues/36)

**Comment by ghost** [comment]
@dieppa 
I've changed the access modifiers for the setters. Awaiting more information about refactoring.

**Comment by dieppa** [comment]
@mbuccat , If your change covers this issue, please open a pull request(from your forked repository) and I review it. It should be pretty easy one. Thanks
