### ISSUE TITLE
Update mongdb-sync-driver for Spring Boot 3.3.X

### ISSUE THREAD

**Issue by alberrogu** [flamingock/mongock#78]
## Description

We need to add support for Spring Boot 3.3.X. The dependency for the mongo-sync driver has been updated to version 5.0.1, which requires compatibility with Spring Boot 3.3.X

## PRIORITY

NORMAL

## Version and environment

Spring Boot 3.3.2 and mongock 5.4.4

### Mongock
- Mongock 5.4.4
- mongodb-springdata-v3-driver

### Environment
- Spring boot 3.3.0

**Comment by osantana85** [comment]
Hello @alberrogu , thanks for raising this issue. Mongock is already compatible with Spring Boot 3.3.2 (current latest version), but you need to use Mongock Driver for SpringData v4.

You can take a look at this sample project using both of them:

[Mongock Example: SpringBoot v3 + SpringData v4](https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot3-springdata4-jdk17)

Hope this helps you. If not, please let us know.

Thanks.

**Comment by rfelgent** [comment]
the same here. I can confirm, that mongock 5.4.0 (and higher) is compatible with spring boot 3.3.x

@osantana85 can we close this issue ?

**Comment by osantana85** [comment]
@rfelgent  Closed, thanks.
